### ISSUE TITLE
An exception occurred processing JSP page /WEB-INF/jsp/selectRegion.jsp at line 36

### ISSUE THREAD

**Issue by znurgl** [kittylyst/VillagePaymentAgent#34]
After registration, login and select country:

```
org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/selectRegion.jsp at line 36||33: |34:                        <td>Region : </td>|35:                        <td><form:select path="idRegion">|36:                             <form:options items="${regionList}" itemValue="id" itemLabel="description" />|37:                         </form:select></td>|38:                    </tr>|39:                    <tr>|||Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:568)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:470)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:405)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:349)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:236)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:257)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1183)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:902)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.hibernate.LazyInitializationException: could not initialize proxy - no Session

**Comment by njacobs5074** [comment]
I can replicate this problem, too, with build c7535e8eeabc6e831e19f31c560f21d386330cdf.

**Comment by jeqo** [comment]
I resolved it commenting all the ``toString()`` methods on model package

**Comment by njacobs5074** [comment]
That's odd.  But, did you see this on SO?
http://stackoverflow.com/questions/21574236/org-hibernate-lazyinitializationexception-could-not-initialize-proxy-no-sess

**Comment by jeqo** [comment]
Yes, but I don't see those modifications on Hibernate configuration. I tried to apply those options (``current_session_context_class`` or ``hibernate.enable_lazy_load_no_trans``) but I get the same exception.

Also the stack trace is different:
```java
org.hibernate.LazyInitializationException: could not initialize proxy - no Session

	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:167)

	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:215)

	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:190)

	at org.haftrust.verifier.model.Country_$$_javassist_0.toString(Country_$$_javassist_0.java)

	at java.lang.String.valueOf(String.java:2981)

	at java.lang.StringBuilder.append(StringBuilder.java:131)

	at org.haftrust.verifier.model.Region.toString(Region.java:52)

	at org.springframework.util.ObjectUtils.nullSafeToString(ObjectUtils.java:547)

```


Comment ``toString()`` methods works for me to go throw the application.

**Comment by njacobs5074** [comment]
Interesting - I guess there's something I don't understand about how Hibernate works with respect to the `toString() method.  Rather than commenting out code, can you just delete them?

Thanks,

Nick

**Comment by kittylyst** [comment]
This is a cargo-cult fix. The toString() methods were added to resolve an earlier problem during the hackday. I would prefer if we understood what was actually causing this problem, rather than just deleting code that "seems to fix the problem". In my experience with Hibernate, this is symptomatic of something deeper & we should look for that (also, don't forget we still need to upgrade Hibernate to a more recent version & to JPA).

-1 on merge.

**Comment by muralimohan123** [comment]
Was going to email that. The stack trace should show where the call to
toString is originating from. The problem, obviously, is that the hibernate
session is closed for that call.

**Comment by jeqo** [comment]
Yes, I know this is not a solution. I just share a way to "by-pass" this exception and go forward on testing the application. I'm agree with @kittylyst that we should find what is causing the problem. I'll work on that later. Regards!

**Comment by gratiartis** [comment]
The problem is that the toString() method in Region is concatenating its Country, which is a different entity, which has not been loaded.

In more up to date versions, I tend to just put a null check on a lazy-loaded reference if I'm concatenating in a toString() method, which works  fine, so I'm guessing that Hibernate 3 must be doing some more invasive AOP.

There are a couple of options for dealing with this in a general fashion.

Add lazy="false" to the many-to-one mapping in region.hbm.xml. There's a slight performance impact due to having to join, but a region only has one country, so it shouldn't be a big performance impact, as I'm assuming that you would generally wish to know which country a region is in.

The alternative would be to ensure that the Hibernate session is opened throughout the life of the view. You can do that with OpenSessionInViewFilter:

    <filter>
      <filter-name>hibernateFilter</filter-name>
      <filter-class>org.springframework.orm.hibernate3.support.OpenSessionInViewFilter</filter-class>
      <init-param>
         <param-name>sessionFactoryBeanName</param-name>
         <param-value>sessionFactory</param-value>         
      </init-param>      
   </filter>

Note that according to http://stackoverflow.com/questions/8435034/configuring-opensessioninviewfilter-with-spring-3-and-servlet-3 that filter needs to come first in the chain.
