### ISSUE TITLE
Error 500 on registerVerifier.htm: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by jeqo** [kittylyst/VillagePaymentAgent#39]
This exception is thrown after add your second Reference and try to complete the registration:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:583)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

...
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(ArrayList.java:653)

	at java.util.ArrayList.get(ArrayList.java:429)

	at 
org.haftrust.verifier.dao.StaticDataDAOImpl.getEmploymentStatus(StaticDataDAOImpl.java:75)

	at org.haftrust.verifier.service.VerifierServiceImpl.registerVerifier(VerifierServiceImpl.java:660)
...

	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)

	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)

	at com.sun.proxy.$Proxy20.registerVerifier(Unknown Source)

	at org.haftrust.verifier.controller.RegisterController.processFinish(RegisterController.java:628)

	at org.springframework.web.servlet.mvc.AbstractWizardFormController.validatePagesAndFinish(AbstractWizardFormController.java:642)

	at org.springframework.web.servlet.mvc.AbstractWizardFormController.processFormSubmission(AbstractWizardFormController.java:492)
	... 23 more
```

Occurs when the following method is called: 

```java
public StaticData getEmploymentStatus(String description) {
        Object[] param = {"employment status", description};
        List l = getHibernateTemplate().find("from StaticData s where s.type=? and s.description=?", param);
        List<StaticData> staticDataList = new ArrayList<StaticData>();
        LOG.debug("static data employment status list size: {}", l.size());
        if (l.size() > 0) {
            for (int i = 0; i < l.size(); i++) {
                StaticData staticData = (StaticData) l.get(i);
                staticDataList.add(staticData);
            }
        }
        return staticDataList.get(0);
    }
```

What is rare here is when I print the description is **empty**, but this is how its called:

```java
this.sdStatus = this.staticDataDao.getEmploymentStatus("Registered");
```

**Comment by gratiartis** [comment]
Two bugs...

    return staticDataList.get(0);

... assumes that there will always be at least one result of a search. Therefore, as there is no employment status "Registered", it throws an IndexOutOfBoundsException, which isn't helpful.

However, the root cause is the DB loader script. 

    INSERT INTO KJ905.HT_STATIC_DATA ("TYPE", "VALUE", DESCRIPTION) VALUES ('employment status', 'registered', 'Registered ');

... where there is a space after "Registered".
