### ISSUE TITLE
Integration Tests failing due to NoClassDefFoundError

### ISSUE THREAD

**Issue by quiram** [kittylyst/VillagePaymentAgent#50]
Not sure if it's my own setup but if I try to run mvn verify on a clean checkout unit tests will pass, but integration tests won't. Details:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.haftrust.verifier.VerifierPreregistrationIntegrationTest
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.027 sec <<< FAILURE! - in org.haftrust.verifier.VerifierPreregistrationIntegrationTest
shouldRegisterVerifierWhenDetailsAreCorrect(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.02 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/htmlunit/corejs/javascript/ContextAction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.setUp(VerifierPreregistrationIntegrationTest.java:31)

shouldRegisterVerifierWhenDetailsAreCorrect(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.021 sec  <<< ERROR!
java.lang.NullPointerException: null
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.tearDown(VerifierPreregistrationIntegrationTest.java:37)

shouldNotRegisterVerifierDetailsWhenPasswordDoesNotMatch(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/htmlunit/corejs/javascript/ContextAction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.setUp(VerifierPreregistrationIntegrationTest.java:31)

shouldNotRegisterVerifierDetailsWhenPasswordDoesNotMatch(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException: null
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.tearDown(VerifierPreregistrationIntegrationTest.java:37)

shouldNotRegisterVerifierDetailsWhenAlreadyRegistered(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: net/sourceforge/htmlunit/corejs/javascript/ContextAction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.setUp(VerifierPreregistrationIntegrationTest.java:31)

shouldNotRegisterVerifierDetailsWhenAlreadyRegistered(org.haftrust.verifier.VerifierPreregistrationIntegrationTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException: null
        at org.haftrust.verifier.VerifierPreregistrationIntegrationTest.tearDown(VerifierPreregistrationIntegrationTest.java:37)

Results :

Tests in error:
org.haftrust.verifier.VerifierPreregistrationIntegrationTest.shouldNotRegisterVerifierDetailsWhenAlreadyRegistered(org.haftrust.verifier.VerifierPreregistration
IntegrationTest)
  Run 1: VerifierPreregistrationIntegrationTest.setUp:31 NoClassDefFound net/sourceforg...
  Run 2: VerifierPreregistrationIntegrationTest.tearDown:37 NullPointer

org.haftrust.verifier.VerifierPreregistrationIntegrationTest.shouldNotRegisterVerifierDetailsWhenPasswordDoesNotMatch(org.haftrust.verifier.VerifierPreregistrat
ionIntegrationTest)
  Run 1: VerifierPreregistrationIntegrationTest.setUp:31 NoClassDefFound net/sourceforg...
  Run 2: VerifierPreregistrationIntegrationTest.tearDown:37 NullPointer

org.haftrust.verifier.VerifierPreregistrationIntegrationTest.shouldRegisterVerifierWhenDetailsAreCorrect(org.haftrust.verifier.VerifierPreregistrationIntegratio
nTest)
  Run 1: VerifierPreregistrationIntegrationTest.setUp:31 NoClassDefFound net/sourceforg...
  Run 2: VerifierPreregistrationIntegrationTest.tearDown:37 NullPointer

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

**Comment by njacobs5074** [comment]
As of 27-02-15 19:30 GMT, I'm not seeing any issues with a clean checkout of master.  I ran:
````
git clone --depth=1 https://github.com/kittylyst/VillagePaymentAgent.git
mvn integration-test
````

**Comment by quiram** [comment]
Could you please share the output? Also, what do you get when you run
`mvn verify`

**Comment by njacobs5074** [comment]
`mvn verify` works fine for me:

````
...
Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
````

**Comment by quiram** [comment]
Ok, then maybe it's my setup... let me take a look and I'll come back to you.

**Comment by quiram** [comment]
Apologies, I had an issue with my local maven cache. Everything is working now, closing this :)
