### ISSUE TITLE
Multi-user capability?

### ISSUE THREAD

**Issue by gratiartis** [kittylyst/VillagePaymentAgent#55]
I have been going through the `VerifierServiceImpl` and how it's used. Something that has jumped out at me is that this seems to be a globally scoped object, which caches all the data sets it queries when it queries them and also holds values relating to the current state of a user journey.

As far as I can tell, this means that if 2 people used the system at the same time, there could be all sorts of bugs hidden away relating to them changing each others data. I came across it myself due to discovering issues with transaction propagation.

A possible interim fix would be to scope the service to a user's session. But this leads to the rather weird situation where every user session pretty much replicates the contents of the database in memory.

My thinking is that it would be good to remove all state from this service. For instance, get rid of all of the lists which are duplicating database tables. Potentially a separate session-scoped service might be useful for tracking just the user progress state, but I'm not sure even that is required.

**Comment by njacobs5074** [comment]
Hi Stephen,

Good find.  The web services layer should be completely stateless or at the
most, it should have session-oriented state.  We definitely need to fix
this.  I can't imagine why there would be any need to cache any of the
information beyond the session since there's so little required.

Again, good find.

Nick

On Sat, Feb 28, 2015 at 10:27 AM, Stephen Masters <notifications@github.com>
wrote:

> I have been going through the VerifierServiceImpl and how it's used.
> Something that has jumped out at me is that this seems to be a globally
> scoped object, which caches all the data sets it queries when it queries
> them and also holds values relating to the current state of a user journey.
>
> As far as I can tell, this means that if 2 people used the system at the
> same time, there could be all sorts of bugs hidden away relating to them
> changing each others data. I came across it myself due to discovering
> issues with transaction propagation.
>
> A possible interim fix would be to scope the service to a user's session.
> But this leads to the rather weird situation where every user session
> pretty much replicates the contents of the database in memory.
>
> My thinking is that it would be good to remove all state from this
> service. For instance, get rid of all of the lists which are duplicating
> database tables. Potentially a separate session-scoped service might be
> useful for tracking just the user progress state, but I'm not sure even
> that is required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kittylyst/VillagePaymentAgent/issues/55>.
>



-- 
Phone: +44 7463 853 913
LinkedIn: http://uk.linkedin.com/in/njacobs5074
Twitter: @njacobs5074

**Comment by njacobs5074** [comment]
Concern seems to be valid.  Here is an error I got on the region verifier web page (`http://localhost:8080/registerVerifier.htm`) while running the app from 2 different browsers.  This was done to ensure they had completely different HTTP sessions.

## Caused by:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: object references an unsaved transient instance - save the transient instance before flushing: org.haftrust.verifier.model.Region; nested exception is org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.haftrust.verifier.model.Region
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: object references an unsaved transient instance - save the transient instance before flushing: org.haftrust.verifier.model.Region; nested exception is org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.haftrust.verifier.model.Region
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:671)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:412)
	at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:375)
	at org.springframework.orm.hibernate3.HibernateTemplate.find(HibernateTemplate.java:913)
	at org.springframework.orm.hibernate3.HibernateTemplate.find(HibernateTemplate.java:909)
	at org.haftrust.verifier.dao.DistrictDAOImpl.getDistricts(DistrictDAOImpl.java:24)
	at org.haftrust.verifier.service.VerifierServiceImpl.getDistrictList(VerifierServiceImpl.java:876)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy20.getDistrictList(Unknown Source)
	at org.haftrust.verifier.controller.RegisterController.districtSelection(RegisterController.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:685)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	... 24 more
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.haftrust.verifier.model.Region
	at org.hibernate.engine.ForeignKeys.getEntityIdentifierIfNotUnsaved(ForeignKeys.java:243)
	at org.hibernate.type.EntityType.getIdentifier(EntityType.java:456)
	at org.hibernate.type.ManyToOneType.nullSafeSet(ManyToOneType.java:130)
	at org.hibernate.param.PositionalParameterSpecification.bind(PositionalParameterSpecification.java:68)
	at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:578)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1716)
	at org.hibernate.loader.Loader.doQuery(Loader.java:801)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
	at org.hibernate.loader.Loader.doList(Loader.java:2542)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
	at org.hibernate.loader.Loader.list(Loader.java:2271)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:459)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:365)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
	at org.springframework.orm.hibernate3.HibernateTemplate$30.doInHibernate(HibernateTemplate.java:922)
	at org.springframework.orm.hibernate3.HibernateTemplate$30.doInHibernate(HibernateTemplate.java:913)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:407)
	... 56 more
```
